Stack update `v2024-04-12` for `aws-mac-baremetal`
bitrise-io/stacks pull request #398
Opened 2024-04-15 12:02 UTC by bitrise-infrabot

2024-04-16 12:48 UTC, ofalvai commented on data/aws-mac-baremetal/stack_rev_id.txt
> +v2024-04-12
FYI This needs to be updated: https://bitrise.atlassian.net/wiki/spaces/RD/pages/2769223763/Building+AWS+AMI+runbook#Bare-metal

2024-04-16 12:49 UTC, ofalvai requested changes
Had one note about the rev ID

2024-04-22 13:53 UTC, pgyula commented on data/aws-mac-baremetal/stack_rev_id.txt
> +v2024-04-12
```suggestion
v2.54.0
```

2024-04-22 14:02 UTC, ofalvai approved these changes

2024-04-22 14:04 UTC, merged